# Generated by Django 4.2.3 on 2023-08-06 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='mail',
        ),
        migrations.AddField(
            model_name='message',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='Тело письма'),
        ),
        migrations.AddField(
            model_name='message',
            name='mail_settings',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.mail', verbose_name='Рассылка'),
        ),
        migrations.AddField(
            model_name='message',
            name='theme',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тема письма'),
        ),
    ]
