# Generated by Django 4.2.3 on 2023-08-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='creation_date',
            field=models.DateField(null=True, verbose_name='Дата создания'),
        ),
    ]
