# Generated by Django 4.2.3 on 2023-08-08 17:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 8, 22, 49, 7, 568810), null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/', verbose_name='Превью'),
        ),
    ]
